### PR TITLE
Fix/max entries

### LINKED ISSUE #22: Unstaking more than `maxEntries` will error and prevent users from unstaking their funds.
The mechanism of unbonding stake and its maxEntries is decribed here in the [cosmos-sdk docs](https://docs.cosmos.network/v0.47/modules/staking#:~:text=existing%20UnbondingDelegation%20has%20maximum%20entries%20as%20defined%20by%20params.MaxEntries).

A quick way to mitigate this issue is by withdrawing users are put into queue and new customers putting money are paying off people from queue first. 

We should also consider Cancelling undelegation when new users add enough funds to pay back undelegating users.

### PR DESCRIPTION
**Pull request by MbBrainz**
Fixes #22 

This is a really hacky but functional solution. 
I made adjusted all the tests so they work with reconcile() (the function that wil undelegate the unconfirmed claims,

A ClaimDetail is unconfirmed if the timestamp is set to None.

Please if you have the time @ueco-jb Add some tests, merge it and preferably also create a new release.

### CODE REVIEW

File: contracts/interstake-yield-generator/src/contract.rs [hunk 1]
```diff
@@ -277,35 +279,77 @@ mod execute {
...
             })?;
 
-        let msgs = delegate_msgs_for_validators(deps.as_ref(), amount.clone(), false)?;
-
-        TOTAL.update(deps.storage, |total| -> StdResult<_> {
-            Ok(coin((total.amount - amount.amount).u128(), total.denom))
-        })?;
+        STAKE_DETAILS.save(deps.storage, &info.sender, &stake_details)?;
 
+        // IMPORTANT: This will only queue the undelegation. The property processed is set to false.
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/contract.rs:284]: > The property processed is set to false.

Please clarify this comment.

File: contracts/interstake-yield-generator/src/msg.rs [hunk 2]
```diff
@@ -50,6 +50,8 @@ pub enum ExecuteMsg {
         amount: Uint128,
         commission_address: Option<String>,
     },
+    /// Start unbonding current batch
+    Reconcile {},
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/msg.rs:54]: Look here at mister big brain eloquent. :D
But to be honest, I'm not sure this is the best name. So you changed `undelegate` to `query_undelegate`, and now undelegating is happening in `reconcile`?

File: contracts/interstake-yield-generator/src/multitest/undelegate.rs [hunk 3]
```diff
@@ -211,14 +228,68 @@ fn unexpired_claims_arent_removed() {
...
-            release_timestamp: current_time.plus_seconds(TWENTY_EIGHT_DAYS / 2)
+            release_timestamp: Some(current_time.plus_seconds(TWENTY_EIGHT_DAYS / 2))
         }]
     );
 }
 
+#[test_case(1, 10; "single_validator ten users")]
+#[test_case(5, 10; "5 validator ten users")]
+#[test_case(1, 13; "1 validator thirdteen users")]
+#[test_case(5, 13; "5 validator thirdteen users")]
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/multitest/undelegate.rs:239]:
```suggestion
#[test_case(1, 13; "1 validator thirteen users")]
#[test_case(5, 13; "5 validator thirteen users")]
```

File: contracts/interstake-yield-generator/src/state.rs [hunk 4]
```diff
@@ -47,14 +49,41 @@ impl StakeDetails {
...
+
+    pub fn now(now: Timestamp) -> Self {
+        UnbondInfo { latest: now }
+    }
+
+    pub fn new(now: Timestamp) -> Self {
+        UnbondInfo {
+            latest: now.minus_seconds(FOUR_DAYS),
+        }
+    }
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/state.rs:83]: I don't like this design where user might think he creates unbond info with given timestamp, and underneath quietly that data is modified.
I don't have better idea right now, but maybe at least indicate it in the name? Something like `new_minus_four_days`, or rename `UnbondInfo` structure to reflect that?

File: contracts/interstake-yield-generator/src/error.rs [hunk 5]
```diff
@@ -48,6 +48,9 @@ pub enum ContractError {
     #[error("Commission address may not be the same as the recipient")]
     CommissionAddressSameAsRecipient {},
 
+    #[error("Unbonding called too soon after last unbonding")]
+    UnbondingTooSoon {},
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/error.rs:52]: This will be used when we go over max entries limit, right? 
I'd rather rephrase that - `Unbonding max_limit exceeded`, please try next day or something?

File: contracts/interstake-yield-generator/src/contract.rs [hunk 6]
```diff
@@ -277,35 +279,77 @@ mod execute {
...
-            .add_attribute("action", "undelegate")
+            .add_attribute("action", "queue_undelegate")
             .add_attribute("sender", info.sender.to_string())
-            .add_attribute("amount", amount.to_string())
-            .add_attribute("release_timestamp", release_timestamp.to_string())
-            .add_messages(msgs))
+            .add_attribute("amount", amount.to_string()))
+    }
+
+    pub fn reconcile(
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/contract.rs:302]: Could you please provide doc comment with description of this solution? It's not that trivial and some of implementation is hidden under abstraction (like subtracting 4 days from unbonding period)

File: contracts/interstake-yield-generator/src/contract.rs [hunk 7]
```diff
@@ -277,35 +279,77 @@ mod execute {
...
+        deps: DepsMut,
+        env: Env,
+        _info: MessageInfo,
+    ) -> Result<Response, ContractError> {
+        UNBOND_INFO.update(
+            deps.storage,
+            |info: UnbondInfo| -> Result<_, ContractError> { info.unbond_now(env.block.time) },
+        )?;
```
Comment (ueco-jb) [inline contracts/interstake-yield-generator/src/contract.rs:310]: So the main gimmick of this helper is - at instantiation you set buffer `current_time - 4 days`.
Then during undelegation you check if that time plus four days is smaller or equal then current time... Which means if at least four days has passed... If so, you set new time as current.

File: contracts/interstake-yield-generator/src/error.rs (hunk 5 above)
Comment (ueco-jb) [reply contracts/interstake-yield-generator/src/error.rs:52]: Okay, I've read rest of implementation. My suggestion doesn't make sense in this context, but I'd still provide at least some info about implementation and what does it mean "too soon" etc.

File: contracts/interstake-yield-generator/src/msg.rs (hunk 2 above)
Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/msg.rs:54]: I got it from Larry, Blame it on him

Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/msg.rs:54]: Btw i didnt change it to `query_undelegate` but to `queue_undelegate`

File: contracts/interstake-yield-generator/src/contract.rs (hunk 1 above)
Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/contract.rs]: This comment is old, i removed it

File: contracts/interstake-yield-generator/src/state.rs (hunk 4 above)
Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/state.rs]: Absolutely... I redesigned the unbond info completely. Its gone entirely and replaced by `Expiration`

File: contracts/interstake-yield-generator/src/error.rs (hunk 5 above)
Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/error.rs]: Definitely. I rephrased the error name and message, to include some more info

File: contracts/interstake-yield-generator/src/contract.rs (hunk 7 above)
Comment (MbBrainz) [reply contracts/interstake-yield-generator/src/contract.rs]: Yea screw that, it was way to unclear. I've replaced the UnbondingInfo in its entirety

**Review by ueco-jb — APPROVED** [review]
